services:
  # grpc-server:
  #   build: .
  #   ports:
  #     - "50051:50051"
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #     - SERVER_PORT=50051
  #     - REDIS_ADDR=redis:6379
  #     - REDIS_PASSWORD=your_password
  #     - REDIS_DB=0
  #   depends_on:
  #     - redis

  explorer:
    image: influxdata/influxdb3-ui:1.4.0
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    volumes:
      - ./explorer/config:/app-root/config:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:2.70.1
    ports:
      - "5540:5540"
    depends_on:
      - redis

  postgres:
    image: postgres:18.1-alpine3.23
    container_name: telemetry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-telemetry_secret_password}
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-db:/docker-entrypoint-initdb.d  # Optional: initialization scripts

  nats:
    image: nats:2.12.4-alpine3.22
    container_name: nats
    restart: unless-stopped
    command: "-m 8222"
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port

volumes:
  postgres_data:
    driver: local
