// telemetry/v1/ingest.proto
//
// Unified protobuf schema for the zc8 telemetry platform.
//
// JetStream subject map (all messages are persisted — no NATS Core):
//
//   data.{orgId}.{teamId}.{deviceKey}.raw      – IngestEnvelope (type=PAYLOAD_RAW)
//   data.{orgId}.{teamId}.{deviceKey}.decoded  – IngestEnvelope (type=PAYLOAD_DECODED)
//   svc.{orgId}.{svcId}                        – ServiceEvent
//   cmd.{orgId}.{teamId}.{deviceKey}           – CommandEnvelope
//
// Three JetStream streams:
//   DATA  – captures data.>
//   SVC   – captures svc.>
//   CMD   – captures cmd.>
//
// Browser consumers use ephemeral ordered JetStream consumers via nats.ws.
// Browser NATS permissions: subscribe data.{orgId}.> and svc.{orgId}.>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ingest.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryIngestService_IngestUnary_FullMethodName  = "/zc8_telemetry_proto_v1.TelemetryIngestService/IngestUnary"
	TelemetryIngestService_IngestStream_FullMethodName = "/zc8_telemetry_proto_v1.TelemetryIngestService/IngestStream"
	TelemetryIngestService_IngestBatch_FullMethodName  = "/zc8_telemetry_proto_v1.TelemetryIngestService/IngestBatch"
)

// TelemetryIngestServiceClient is the client API for TelemetryIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelemetryIngestService — for direct gRPC input adapters.
type TelemetryIngestServiceClient interface {
	IngestUnary(ctx context.Context, in *IngestEnvelope, opts ...grpc.CallOption) (*IngestAck, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestEnvelope, IngestAck], error)
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchAck, error)
}

type telemetryIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryIngestServiceClient(cc grpc.ClientConnInterface) TelemetryIngestServiceClient {
	return &telemetryIngestServiceClient{cc}
}

func (c *telemetryIngestServiceClient) IngestUnary(ctx context.Context, in *IngestEnvelope, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, TelemetryIngestService_IngestUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIngestServiceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestEnvelope, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryIngestService_ServiceDesc.Streams[0], TelemetryIngestService_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestEnvelope, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngestService_IngestStreamClient = grpc.BidiStreamingClient[IngestEnvelope, IngestAck]

func (c *telemetryIngestServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchAck)
	err := c.cc.Invoke(ctx, TelemetryIngestService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryIngestServiceServer is the server API for TelemetryIngestService service.
// All implementations must embed UnimplementedTelemetryIngestServiceServer
// for forward compatibility.
//
// TelemetryIngestService — for direct gRPC input adapters.
type TelemetryIngestServiceServer interface {
	IngestUnary(context.Context, *IngestEnvelope) (*IngestAck, error)
	IngestStream(grpc.BidiStreamingServer[IngestEnvelope, IngestAck]) error
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchAck, error)
	mustEmbedUnimplementedTelemetryIngestServiceServer()
}

// UnimplementedTelemetryIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryIngestServiceServer struct{}

func (UnimplementedTelemetryIngestServiceServer) IngestUnary(context.Context, *IngestEnvelope) (*IngestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestUnary not implemented")
}
func (UnimplementedTelemetryIngestServiceServer) IngestStream(grpc.BidiStreamingServer[IngestEnvelope, IngestAck]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedTelemetryIngestServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedTelemetryIngestServiceServer) mustEmbedUnimplementedTelemetryIngestServiceServer() {
}
func (UnimplementedTelemetryIngestServiceServer) testEmbeddedByValue() {}

// UnsafeTelemetryIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryIngestServiceServer will
// result in compilation errors.
type UnsafeTelemetryIngestServiceServer interface {
	mustEmbedUnimplementedTelemetryIngestServiceServer()
}

func RegisterTelemetryIngestServiceServer(s grpc.ServiceRegistrar, srv TelemetryIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryIngestService_ServiceDesc, srv)
}

func _TelemetryIngestService_IngestUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIngestServiceServer).IngestUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIngestService_IngestUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIngestServiceServer).IngestUnary(ctx, req.(*IngestEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIngestService_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryIngestServiceServer).IngestStream(&grpc.GenericServerStream[IngestEnvelope, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryIngestService_IngestStreamServer = grpc.BidiStreamingServer[IngestEnvelope, IngestAck]

func _TelemetryIngestService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIngestServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIngestService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIngestServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryIngestService_ServiceDesc is the grpc.ServiceDesc for TelemetryIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zc8_telemetry_proto_v1.TelemetryIngestService",
	HandlerType: (*TelemetryIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestUnary",
			Handler:    _TelemetryIngestService_IngestUnary_Handler,
		},
		{
			MethodName: "IngestBatch",
			Handler:    _TelemetryIngestService_IngestBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _TelemetryIngestService_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ingest.proto",
}

const (
	CommandService_SendCommand_FullMethodName   = "/zc8_telemetry_proto_v1.CommandService/SendCommand"
	CommandService_CommandStream_FullMethodName = "/zc8_telemetry_proto_v1.CommandService/CommandStream"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommandService — bidirectional between API and command dispatch workers.
type CommandServiceClient interface {
	SendCommand(ctx context.Context, in *CommandEnvelope, opts ...grpc.CallOption) (*CommandAck, error)
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandEnvelope, CommandAck], error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) SendCommand(ctx context.Context, in *CommandEnvelope, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, CommandService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandEnvelope, CommandAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], CommandService_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandEnvelope, CommandAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_CommandStreamClient = grpc.BidiStreamingClient[CommandEnvelope, CommandAck]

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
//
// CommandService — bidirectional between API and command dispatch workers.
type CommandServiceServer interface {
	SendCommand(context.Context, *CommandEnvelope) (*CommandAck, error)
	CommandStream(grpc.BidiStreamingServer[CommandEnvelope, CommandAck]) error
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) SendCommand(context.Context, *CommandEnvelope) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedCommandServiceServer) CommandStream(grpc.BidiStreamingServer[CommandEnvelope, CommandAck]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendCommand(ctx, req.(*CommandEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServiceServer).CommandStream(&grpc.GenericServerStream[CommandEnvelope, CommandAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_CommandStreamServer = grpc.BidiStreamingServer[CommandEnvelope, CommandAck]

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zc8_telemetry_proto_v1.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _CommandService_SendCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _CommandService_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ingest.proto",
}
