// telemetry/v1/ingest.proto
//
// Unified protobuf schema for the zc8 telemetry platform.
//
// JetStream subject map (all messages are persisted — no NATS Core):
//
//   data.{orgId}.{teamId}.{deviceKey}.raw      – IngestEnvelope (type=PAYLOAD_RAW)
//   data.{orgId}.{teamId}.{deviceKey}.decoded  – IngestEnvelope (type=PAYLOAD_DECODED)
//   svc.{orgId}.{svcId}                        – ServiceEvent
//   cmd.{orgId}.{teamId}.{deviceKey}           – CommandEnvelope
//
// Three JetStream streams:
//   DATA  – captures data.>
//   SVC   – captures svc.>
//   CMD   – captures cmd.>
//
// Browser consumers use ephemeral ordered JetStream consumers via nats.ws.
// Browser NATS permissions: subscribe data.{orgId}.> and svc.{orgId}.>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ingest.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestSource int32

const (
	IngestSource_SOURCE_UNSPECIFIED IngestSource = 0
	IngestSource_SOURCE_MQTT        IngestSource = 1
	IngestSource_SOURCE_GRPC        IngestSource = 2
	IngestSource_SOURCE_HTTP        IngestSource = 3
	IngestSource_SOURCE_CLI         IngestSource = 4
)

// Enum value maps for IngestSource.
var (
	IngestSource_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_MQTT",
		2: "SOURCE_GRPC",
		3: "SOURCE_HTTP",
		4: "SOURCE_CLI",
	}
	IngestSource_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_MQTT":        1,
		"SOURCE_GRPC":        2,
		"SOURCE_HTTP":        3,
		"SOURCE_CLI":         4,
	}
)

func (x IngestSource) Enum() *IngestSource {
	p := new(IngestSource)
	*p = x
	return p
}

func (x IngestSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestSource) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[0].Descriptor()
}

func (IngestSource) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[0]
}

func (x IngestSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestSource.Descriptor instead.
func (IngestSource) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

type PayloadType int32

const (
	PayloadType_PAYLOAD_UNSPECIFIED PayloadType = 0
	PayloadType_PAYLOAD_RAW         PayloadType = 1 // Raw bytes from device – primary for audit log
	PayloadType_PAYLOAD_DECODED     PayloadType = 2 // Parsed + enriched – streamed to all output services
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0: "PAYLOAD_UNSPECIFIED",
		1: "PAYLOAD_RAW",
		2: "PAYLOAD_DECODED",
	}
	PayloadType_value = map[string]int32{
		"PAYLOAD_UNSPECIFIED": 0,
		"PAYLOAD_RAW":         1,
		"PAYLOAD_DECODED":     2,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[1].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[1]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

type ValueType int32

const (
	ValueType_VALUE_UNSPECIFIED ValueType = 0
	ValueType_VALUE_FLOAT       ValueType = 1
	ValueType_VALUE_INT         ValueType = 2
	ValueType_VALUE_BOOL        ValueType = 3
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_UNSPECIFIED",
		1: "VALUE_FLOAT",
		2: "VALUE_INT",
		3: "VALUE_BOOL",
	}
	ValueType_value = map[string]int32{
		"VALUE_UNSPECIFIED": 0,
		"VALUE_FLOAT":       1,
		"VALUE_INT":         2,
		"VALUE_BOOL":        3,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[2].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[2]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

type ServiceEventType int32

const (
	ServiceEventType_SVC_EVENT_UNSPECIFIED ServiceEventType = 0
	ServiceEventType_SVC_HEARTBEAT         ServiceEventType = 1 // Adapter alive
	ServiceEventType_SVC_TOMBSTONE         ServiceEventType = 2 // Adapter stopped
	ServiceEventType_SVC_RAW_INGEST        ServiceEventType = 3 // Raw message received (before parsing)
	ServiceEventType_SVC_OUTPUT_ACK        ServiceEventType = 4 // Output service wrote records
)

// Enum value maps for ServiceEventType.
var (
	ServiceEventType_name = map[int32]string{
		0: "SVC_EVENT_UNSPECIFIED",
		1: "SVC_HEARTBEAT",
		2: "SVC_TOMBSTONE",
		3: "SVC_RAW_INGEST",
		4: "SVC_OUTPUT_ACK",
	}
	ServiceEventType_value = map[string]int32{
		"SVC_EVENT_UNSPECIFIED": 0,
		"SVC_HEARTBEAT":         1,
		"SVC_TOMBSTONE":         2,
		"SVC_RAW_INGEST":        3,
		"SVC_OUTPUT_ACK":        4,
	}
)

func (x ServiceEventType) Enum() *ServiceEventType {
	p := new(ServiceEventType)
	*p = x
	return p
}

func (x ServiceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[3].Descriptor()
}

func (ServiceEventType) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[3]
}

func (x ServiceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceEventType.Descriptor instead.
func (ServiceEventType) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{3}
}

// DeviceTags carries physical location and asset classification.
// Resolved at the transport layer and forwarded as InfluxDB tags on every
// decoded payload — no Postgres join on the hot path.
type DeviceTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeM     float64                `protobuf:"fixed64,3,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`
	LocationName  string                 `protobuf:"bytes,4,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	AssetId       string                 `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`                                                        // arbitrary asset identifier
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`                                                                     // "energy" | "water" | "hvac" | "environment" | …
	Extra         map[string]string      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional custom tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTags) Reset() {
	*x = DeviceTags{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTags) ProtoMessage() {}

func (x *DeviceTags) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTags.ProtoReflect.Descriptor instead.
func (*DeviceTags) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceTags) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DeviceTags) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DeviceTags) GetAltitudeM() float64 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *DeviceTags) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *DeviceTags) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *DeviceTags) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DeviceTags) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// SensorCalibration — linear correction for one sensor type.
// calibrated = raw * scale + offset
type SensorCalibration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorType    string                 `protobuf:"bytes,1,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`   // default 1.0  (no correction)
	Offset        float64                `protobuf:"fixed64,3,opt,name=offset,proto3" json:"offset,omitempty"` // default 0.0
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorCalibration) Reset() {
	*x = SensorCalibration{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorCalibration) ProtoMessage() {}

func (x *SensorCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorCalibration.ProtoReflect.Descriptor instead.
func (*SensorCalibration) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *SensorCalibration) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorCalibration) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *SensorCalibration) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SensorCalibration) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// DeviceContext is resolved once at the transport layer and attached to every
// IngestEnvelope, eliminating per-message DB lookups on the hot path.
type DeviceContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey       uint64                 `protobuf:"varint,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	OrganizationId  int64                  `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId          int64                  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // UUID from devices table
	DeviceModelCode string                 `protobuf:"bytes,5,opt,name=device_model_code,json=deviceModelCode,proto3" json:"device_model_code,omitempty"`
	VendorId        int64                  `protobuf:"varint,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ParserId        uint32                 `protobuf:"varint,7,opt,name=parser_id,json=parserId,proto3" json:"parser_id,omitempty"` // Binary parser id
	Tags            *DeviceTags            `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	Calibrations    []*SensorCalibration   `protobuf:"bytes,9,rep,name=calibrations,proto3" json:"calibrations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceContext) Reset() {
	*x = DeviceContext{}
	mi := &file_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceContext) ProtoMessage() {}

func (x *DeviceContext) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceContext.ProtoReflect.Descriptor instead.
func (*DeviceContext) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceContext) GetDeviceKey() uint64 {
	if x != nil {
		return x.DeviceKey
	}
	return 0
}

func (x *DeviceContext) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *DeviceContext) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *DeviceContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceContext) GetDeviceModelCode() string {
	if x != nil {
		return x.DeviceModelCode
	}
	return ""
}

func (x *DeviceContext) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *DeviceContext) GetParserId() uint32 {
	if x != nil {
		return x.ParserId
	}
	return 0
}

func (x *DeviceContext) GetTags() *DeviceTags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DeviceContext) GetCalibrations() []*SensorCalibration {
	if x != nil {
		return x.Calibrations
	}
	return nil
}

type IngestEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`    // ULID — idempotency key
	Ts        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`                             // Event timestamp (device time when available)
	IngestTs  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ingest_ts,json=ingestTs,proto3" json:"ingest_ts,omitempty"` // Wall-clock time at transport layer
	Source    IngestSource           `protobuf:"varint,4,opt,name=source,proto3,enum=zc8_telemetry_proto_v1.IngestSource" json:"source,omitempty"`
	Type      PayloadType            `protobuf:"varint,5,opt,name=type,proto3,enum=zc8_telemetry_proto_v1.PayloadType" json:"type,omitempty"`
	DeviceKey uint64                 `protobuf:"varint,6,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Context   *DeviceContext         `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IngestEnvelope_Raw
	//	*IngestEnvelope_Decoded
	Payload       isIngestEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEnvelope) Reset() {
	*x = IngestEnvelope{}
	mi := &file_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEnvelope) ProtoMessage() {}

func (x *IngestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEnvelope.ProtoReflect.Descriptor instead.
func (*IngestEnvelope) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *IngestEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *IngestEnvelope) GetIngestTs() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestTs
	}
	return nil
}

func (x *IngestEnvelope) GetSource() IngestSource {
	if x != nil {
		return x.Source
	}
	return IngestSource_SOURCE_UNSPECIFIED
}

func (x *IngestEnvelope) GetType() PayloadType {
	if x != nil {
		return x.Type
	}
	return PayloadType_PAYLOAD_UNSPECIFIED
}

func (x *IngestEnvelope) GetDeviceKey() uint64 {
	if x != nil {
		return x.DeviceKey
	}
	return 0
}

func (x *IngestEnvelope) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *IngestEnvelope) GetPayload() isIngestEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestEnvelope) GetRaw() *RawPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestEnvelope_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *IngestEnvelope) GetDecoded() *DecodedPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestEnvelope_Decoded); ok {
			return x.Decoded
		}
	}
	return nil
}

type isIngestEnvelope_Payload interface {
	isIngestEnvelope_Payload()
}

type IngestEnvelope_Raw struct {
	Raw *RawPayload `protobuf:"bytes,8,opt,name=raw,proto3,oneof"`
}

type IngestEnvelope_Decoded struct {
	Decoded *DecodedPayload `protobuf:"bytes,9,opt,name=decoded,proto3,oneof"`
}

func (*IngestEnvelope_Raw) isIngestEnvelope_Payload() {}

func (*IngestEnvelope_Decoded) isIngestEnvelope_Payload() {}

type RawPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                  // Raw bytes as received
	SourceTopic   string                 `protobuf:"bytes,2,opt,name=source_topic,json=sourceTopic,proto3" json:"source_topic,omitempty"` // MQTT topic / HTTP path / gRPC method
	ServiceId     int64                  `protobuf:"varint,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`      // Input service (services.id)
	GatewayEui    string                 `protobuf:"bytes,4,opt,name=gateway_eui,json=gatewayEui,proto3" json:"gateway_eui,omitempty"`    // LoRaWAN gateway EUI (optional)
	Rssi          int32                  `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`                                 // Signal strength dBm (optional)
	Snr           float32                `protobuf:"fixed32,6,opt,name=snr,proto3" json:"snr,omitempty"`                                  // Signal-to-noise ratio dB (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPayload) Reset() {
	*x = RawPayload{}
	mi := &file_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPayload) ProtoMessage() {}

func (x *RawPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPayload.ProtoReflect.Descriptor instead.
func (*RawPayload) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *RawPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawPayload) GetSourceTopic() string {
	if x != nil {
		return x.SourceTopic
	}
	return ""
}

func (x *RawPayload) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RawPayload) GetGatewayEui() string {
	if x != nil {
		return x.GatewayEui
	}
	return ""
}

func (x *RawPayload) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *RawPayload) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

type SensorField struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SensorType string                 `protobuf:"bytes,1,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`                                     // e.g. "a_plus", "p_total", "temperature"
	ValueType  ValueType              `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=zc8_telemetry_proto_v1.ValueType" json:"value_type,omitempty"` // discriminator for query / UI
	// Exactly one is populated (matching value_type)
	ValueFloat float64 `protobuf:"fixed64,3,opt,name=value_float,json=valueFloat,proto3" json:"value_float,omitempty"`
	ValueInt   int64   `protobuf:"varint,4,opt,name=value_int,json=valueInt,proto3" json:"value_int,omitempty"`
	ValueBool  bool    `protobuf:"varint,5,opt,name=value_bool,json=valueBool,proto3" json:"value_bool,omitempty"`
	// Calibration snapshot at time of write
	Scale  float64 `protobuf:"fixed64,6,opt,name=scale,proto3" json:"scale,omitempty"`   // default 1.0
	Offset float64 `protobuf:"fixed64,7,opt,name=offset,proto3" json:"offset,omitempty"` // default 0.0
	// Pre-computed: calibrated = value_float * scale + offset
	CalibratedValue float64 `protobuf:"fixed64,8,opt,name=calibrated_value,json=calibratedValue,proto3" json:"calibrated_value,omitempty"`
	Unit            string  `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorField) Reset() {
	*x = SensorField{}
	mi := &file_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorField) ProtoMessage() {}

func (x *SensorField) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorField.ProtoReflect.Descriptor instead.
func (*SensorField) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *SensorField) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorField) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_VALUE_UNSPECIFIED
}

func (x *SensorField) GetValueFloat() float64 {
	if x != nil {
		return x.ValueFloat
	}
	return 0
}

func (x *SensorField) GetValueInt() int64 {
	if x != nil {
		return x.ValueInt
	}
	return 0
}

func (x *SensorField) GetValueBool() bool {
	if x != nil {
		return x.ValueBool
	}
	return false
}

func (x *SensorField) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *SensorField) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SensorField) GetCalibratedValue() float64 {
	if x != nil {
		return x.CalibratedValue
	}
	return 0
}

func (x *SensorField) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type DecodedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InfluxDB3 measurement name (default: "sensor_data")
	Measurement string `protobuf:"bytes,1,opt,name=measurement,proto3" json:"measurement,omitempty"`
	// Identity tags (written as InfluxDB tags)
	OrgId     string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TeamId    string `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DeviceKey string `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	ModelCode string `protobuf:"bytes,5,opt,name=model_code,json=modelCode,proto3" json:"model_code,omitempty"`
	VendorId  string `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	// Location tags
	Latitude     float64 `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude    float64 `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeM    float64 `protobuf:"fixed64,9,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`
	LocationName string  `protobuf:"bytes,10,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	// Asset tags
	AssetId  string `protobuf:"bytes,11,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Category string `protobuf:"bytes,12,opt,name=category,proto3" json:"category,omitempty"`
	// Custom extra tags
	ExtraTags map[string]string `protobuf:"bytes,13,rep,name=extra_tags,json=extraTags,proto3" json:"extra_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sensor readings — one per sensor type in this message
	Fields []*SensorField `protobuf:"bytes,14,rep,name=fields,proto3" json:"fields,omitempty"`
	// Input service that produced this decoded payload
	ServiceId     int64 `protobuf:"varint,15,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedPayload) Reset() {
	*x = DecodedPayload{}
	mi := &file_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedPayload) ProtoMessage() {}

func (x *DecodedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedPayload.ProtoReflect.Descriptor instead.
func (*DecodedPayload) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *DecodedPayload) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

func (x *DecodedPayload) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DecodedPayload) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DecodedPayload) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *DecodedPayload) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *DecodedPayload) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *DecodedPayload) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DecodedPayload) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DecodedPayload) GetAltitudeM() float64 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *DecodedPayload) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *DecodedPayload) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *DecodedPayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DecodedPayload) GetExtraTags() map[string]string {
	if x != nil {
		return x.ExtraTags
	}
	return nil
}

func (x *DecodedPayload) GetFields() []*SensorField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DecodedPayload) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type ServiceEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventType   ServiceEventType       `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=zc8_telemetry_proto_v1.ServiceEventType" json:"event_type,omitempty"`
	ServiceId   int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceType string                 `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"` // e.g. "input.mqtt"
	OrgId       int64                  `protobuf:"varint,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TeamId      int64                  `protobuf:"varint,5,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName    string                 `protobuf:"bytes,6,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	ReportedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	// SVC_HEARTBEAT / SVC_TOMBSTONE fields
	IsConnected   bool                   `protobuf:"varint,8,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	IsRunning     bool                   `protobuf:"varint,9,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	MessageCount  int64                  `protobuf:"varint,10,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,11,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	Broker        string                 `protobuf:"bytes,13,opt,name=broker,proto3" json:"broker,omitempty"` // MQTT broker / InfluxDB host / gRPC endpoint
	Topics        []string               `protobuf:"bytes,14,rep,name=topics,proto3" json:"topics,omitempty"` // MQTT subscribed topics
	// SVC_RAW_INGEST fields (input adapters only)
	DeviceKey      uint64 `protobuf:"varint,15,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	SourceTopic    string `protobuf:"bytes,16,opt,name=source_topic,json=sourceTopic,proto3" json:"source_topic,omitempty"`
	PayloadPreview []byte `protobuf:"bytes,17,opt,name=payload_preview,json=payloadPreview,proto3" json:"payload_preview,omitempty"` // First 64 bytes
	PayloadSize    int32  `protobuf:"varint,18,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	// SVC_OUTPUT_ACK fields (output adapters only)
	RecordsWritten int32  `protobuf:"varint,19,opt,name=records_written,json=recordsWritten,proto3" json:"records_written,omitempty"`
	Target         string `protobuf:"bytes,20,opt,name=target,proto3" json:"target,omitempty"` // InfluxDB bucket / MQTT topic / HTTP endpoint
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceEvent) Reset() {
	*x = ServiceEvent{}
	mi := &file_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEvent) ProtoMessage() {}

func (x *ServiceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEvent.ProtoReflect.Descriptor instead.
func (*ServiceEvent) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceEvent) GetEventType() ServiceEventType {
	if x != nil {
		return x.EventType
	}
	return ServiceEventType_SVC_EVENT_UNSPECIFIED
}

func (x *ServiceEvent) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ServiceEvent) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceEvent) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ServiceEvent) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ServiceEvent) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *ServiceEvent) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

func (x *ServiceEvent) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *ServiceEvent) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *ServiceEvent) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ServiceEvent) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ServiceEvent) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *ServiceEvent) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *ServiceEvent) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ServiceEvent) GetDeviceKey() uint64 {
	if x != nil {
		return x.DeviceKey
	}
	return 0
}

func (x *ServiceEvent) GetSourceTopic() string {
	if x != nil {
		return x.SourceTopic
	}
	return ""
}

func (x *ServiceEvent) GetPayloadPreview() []byte {
	if x != nil {
		return x.PayloadPreview
	}
	return nil
}

func (x *ServiceEvent) GetPayloadSize() int32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *ServiceEvent) GetRecordsWritten() int32 {
	if x != nil {
		return x.RecordsWritten
	}
	return 0
}

func (x *ServiceEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CommandEnvelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CommandId   string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DeviceId    string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // UUID
	DeviceKey   uint64                 `protobuf:"varint,3,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	DevEui      string                 `protobuf:"bytes,4,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`                // LoRaWAN EUI (optional)
	CommandType string                 `protobuf:"bytes,5,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // "downlink_raw" | "reboot" | "set_config"
	Payload     []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                            // JSON-encoded command data
	// Transport routing (pre-resolved — no DB lookup on dispatch path)
	TransportType   string `protobuf:"bytes,7,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"` // "mqtt" | "http" | "grpc"
	LnsProviderCode string `protobuf:"bytes,8,opt,name=lns_provider_code,json=lnsProviderCode,proto3" json:"lns_provider_code,omitempty"`
	FormatterCode   string `protobuf:"bytes,9,opt,name=formatter_code,json=formatterCode,proto3" json:"formatter_code,omitempty"`
	// MQTT
	MqttHost     string `protobuf:"bytes,10,opt,name=mqtt_host,json=mqttHost,proto3" json:"mqtt_host,omitempty"`
	MqttPort     int32  `protobuf:"varint,11,opt,name=mqtt_port,json=mqttPort,proto3" json:"mqtt_port,omitempty"`
	MqttUsername string `protobuf:"bytes,12,opt,name=mqtt_username,json=mqttUsername,proto3" json:"mqtt_username,omitempty"`
	MqttPassword string `protobuf:"bytes,13,opt,name=mqtt_password,json=mqttPassword,proto3" json:"mqtt_password,omitempty"`
	MqttQos      int32  `protobuf:"varint,14,opt,name=mqtt_qos,json=mqttQos,proto3" json:"mqtt_qos,omitempty"`
	MqttUseTls   bool   `protobuf:"varint,15,opt,name=mqtt_use_tls,json=mqttUseTls,proto3" json:"mqtt_use_tls,omitempty"`
	// HTTP
	HttpBaseUrl         string `protobuf:"bytes,16,opt,name=http_base_url,json=httpBaseUrl,proto3" json:"http_base_url,omitempty"`
	HttpMethod          string `protobuf:"bytes,17,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpAuthType        string `protobuf:"bytes,18,opt,name=http_auth_type,json=httpAuthType,proto3" json:"http_auth_type,omitempty"`
	HttpAuthCredentials string `protobuf:"bytes,19,opt,name=http_auth_credentials,json=httpAuthCredentials,proto3" json:"http_auth_credentials,omitempty"`
	HttpTimeoutSec      int32  `protobuf:"varint,20,opt,name=http_timeout_sec,json=httpTimeoutSec,proto3" json:"http_timeout_sec,omitempty"`
	HttpContentType     string `protobuf:"bytes,21,opt,name=http_content_type,json=httpContentType,proto3" json:"http_content_type,omitempty"`
	// gRPC
	GrpcHost        string `protobuf:"bytes,22,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	GrpcPort        int32  `protobuf:"varint,23,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	GrpcServiceName string `protobuf:"bytes,24,opt,name=grpc_service_name,json=grpcServiceName,proto3" json:"grpc_service_name,omitempty"`
	// Context
	OrganizationId  int64  `protobuf:"varint,25,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TeamId          int64  `protobuf:"varint,26,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DeviceModelCode string `protobuf:"bytes,27,opt,name=device_model_code,json=deviceModelCode,proto3" json:"device_model_code,omitempty"`
	VendorCode      string `protobuf:"bytes,28,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	DeviceMetadata  []byte `protobuf:"bytes,29,opt,name=device_metadata,json=deviceMetadata,proto3" json:"device_metadata,omitempty"` // JSON
	// Timing
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,32,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Attempt       int32                  `protobuf:"varint,33,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *CommandEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandEnvelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommandEnvelope) GetDeviceKey() uint64 {
	if x != nil {
		return x.DeviceKey
	}
	return 0
}

func (x *CommandEnvelope) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *CommandEnvelope) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *CommandEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandEnvelope) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *CommandEnvelope) GetLnsProviderCode() string {
	if x != nil {
		return x.LnsProviderCode
	}
	return ""
}

func (x *CommandEnvelope) GetFormatterCode() string {
	if x != nil {
		return x.FormatterCode
	}
	return ""
}

func (x *CommandEnvelope) GetMqttHost() string {
	if x != nil {
		return x.MqttHost
	}
	return ""
}

func (x *CommandEnvelope) GetMqttPort() int32 {
	if x != nil {
		return x.MqttPort
	}
	return 0
}

func (x *CommandEnvelope) GetMqttUsername() string {
	if x != nil {
		return x.MqttUsername
	}
	return ""
}

func (x *CommandEnvelope) GetMqttPassword() string {
	if x != nil {
		return x.MqttPassword
	}
	return ""
}

func (x *CommandEnvelope) GetMqttQos() int32 {
	if x != nil {
		return x.MqttQos
	}
	return 0
}

func (x *CommandEnvelope) GetMqttUseTls() bool {
	if x != nil {
		return x.MqttUseTls
	}
	return false
}

func (x *CommandEnvelope) GetHttpBaseUrl() string {
	if x != nil {
		return x.HttpBaseUrl
	}
	return ""
}

func (x *CommandEnvelope) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *CommandEnvelope) GetHttpAuthType() string {
	if x != nil {
		return x.HttpAuthType
	}
	return ""
}

func (x *CommandEnvelope) GetHttpAuthCredentials() string {
	if x != nil {
		return x.HttpAuthCredentials
	}
	return ""
}

func (x *CommandEnvelope) GetHttpTimeoutSec() int32 {
	if x != nil {
		return x.HttpTimeoutSec
	}
	return 0
}

func (x *CommandEnvelope) GetHttpContentType() string {
	if x != nil {
		return x.HttpContentType
	}
	return ""
}

func (x *CommandEnvelope) GetGrpcHost() string {
	if x != nil {
		return x.GrpcHost
	}
	return ""
}

func (x *CommandEnvelope) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *CommandEnvelope) GetGrpcServiceName() string {
	if x != nil {
		return x.GrpcServiceName
	}
	return ""
}

func (x *CommandEnvelope) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *CommandEnvelope) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CommandEnvelope) GetDeviceModelCode() string {
	if x != nil {
		return x.DeviceModelCode
	}
	return ""
}

func (x *CommandEnvelope) GetVendorCode() string {
	if x != nil {
		return x.VendorCode
	}
	return ""
}

func (x *CommandEnvelope) GetDeviceMetadata() []byte {
	if x != nil {
		return x.DeviceMetadata
	}
	return nil
}

func (x *CommandEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommandEnvelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CommandEnvelope) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CommandEnvelope) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type CommandAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	AcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandAck) GetAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcknowledgedAt
	}
	return nil
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	IngestTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ingest_time,json=ingestTime,proto3" json:"ingest_time,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // non-empty on rejection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *IngestAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestAck) GetIngestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestTime
	}
	return nil
}

func (x *IngestAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*IngestEnvelope      `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *IngestBatchRequest) GetEnvelopes() []*IngestEnvelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

type IngestBatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*IngestAck           `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchAck) Reset() {
	*x = IngestBatchAck{}
	mi := &file_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchAck) ProtoMessage() {}

func (x *IngestBatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchAck.ProtoReflect.Descriptor instead.
func (*IngestBatchAck) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *IngestBatchAck) GetAcks() []*IngestAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *IngestBatchAck) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestBatchAck) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\x16zc8_telemetry_proto_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n" +
	"\n" +
	"DeviceTags\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x03 \x01(\x01R\taltitudeM\x12#\n" +
	"\rlocation_name\x18\x04 \x01(\tR\flocationName\x12\x19\n" +
	"\basset_id\x18\x05 \x01(\tR\aassetId\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12C\n" +
	"\x05extra\x18\a \x03(\v2-.zc8_telemetry_proto_v1.DeviceTags.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x11SensorCalibration\x12\x1f\n" +
	"\vsensor_type\x18\x01 \x01(\tR\n" +
	"sensorType\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x01R\x06offset\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"\xfa\x02\n" +
	"\rDeviceContext\x12\x1d\n" +
	"\n" +
	"device_key\x18\x01 \x01(\x04R\tdeviceKey\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\x03R\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_model_code\x18\x05 \x01(\tR\x0fdeviceModelCode\x12\x1b\n" +
	"\tvendor_id\x18\x06 \x01(\x03R\bvendorId\x12\x1b\n" +
	"\tparser_id\x18\a \x01(\rR\bparserId\x126\n" +
	"\x04tags\x18\b \x01(\v2\".zc8_telemetry_proto_v1.DeviceTagsR\x04tags\x12M\n" +
	"\fcalibrations\x18\t \x03(\v2).zc8_telemetry_proto_v1.SensorCalibrationR\fcalibrations\"\xee\x03\n" +
	"\x0eIngestEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x127\n" +
	"\tingest_ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bingestTs\x12<\n" +
	"\x06source\x18\x04 \x01(\x0e2$.zc8_telemetry_proto_v1.IngestSourceR\x06source\x127\n" +
	"\x04type\x18\x05 \x01(\x0e2#.zc8_telemetry_proto_v1.PayloadTypeR\x04type\x12\x1d\n" +
	"\n" +
	"device_key\x18\x06 \x01(\x04R\tdeviceKey\x12?\n" +
	"\acontext\x18\a \x01(\v2%.zc8_telemetry_proto_v1.DeviceContextR\acontext\x126\n" +
	"\x03raw\x18\b \x01(\v2\".zc8_telemetry_proto_v1.RawPayloadH\x00R\x03raw\x12B\n" +
	"\adecoded\x18\t \x01(\v2&.zc8_telemetry_proto_v1.DecodedPayloadH\x00R\adecodedB\t\n" +
	"\apayload\"\xa9\x01\n" +
	"\n" +
	"RawPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fsource_topic\x18\x02 \x01(\tR\vsourceTopic\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\x03R\tserviceId\x12\x1f\n" +
	"\vgateway_eui\x18\x04 \x01(\tR\n" +
	"gatewayEui\x12\x12\n" +
	"\x04rssi\x18\x05 \x01(\x05R\x04rssi\x12\x10\n" +
	"\x03snr\x18\x06 \x01(\x02R\x03snr\"\xba\x02\n" +
	"\vSensorField\x12\x1f\n" +
	"\vsensor_type\x18\x01 \x01(\tR\n" +
	"sensorType\x12@\n" +
	"\n" +
	"value_type\x18\x02 \x01(\x0e2!.zc8_telemetry_proto_v1.ValueTypeR\tvalueType\x12\x1f\n" +
	"\vvalue_float\x18\x03 \x01(\x01R\n" +
	"valueFloat\x12\x1b\n" +
	"\tvalue_int\x18\x04 \x01(\x03R\bvalueInt\x12\x1d\n" +
	"\n" +
	"value_bool\x18\x05 \x01(\bR\tvalueBool\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\x01R\x05scale\x12\x16\n" +
	"\x06offset\x18\a \x01(\x01R\x06offset\x12)\n" +
	"\x10calibrated_value\x18\b \x01(\x01R\x0fcalibratedValue\x12\x12\n" +
	"\x04unit\x18\t \x01(\tR\x04unit\"\xe2\x04\n" +
	"\x0eDecodedPayload\x12 \n" +
	"\vmeasurement\x18\x01 \x01(\tR\vmeasurement\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"device_key\x18\x04 \x01(\tR\tdeviceKey\x12\x1d\n" +
	"\n" +
	"model_code\x18\x05 \x01(\tR\tmodelCode\x12\x1b\n" +
	"\tvendor_id\x18\x06 \x01(\tR\bvendorId\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\t \x01(\x01R\taltitudeM\x12#\n" +
	"\rlocation_name\x18\n" +
	" \x01(\tR\flocationName\x12\x19\n" +
	"\basset_id\x18\v \x01(\tR\aassetId\x12\x1a\n" +
	"\bcategory\x18\f \x01(\tR\bcategory\x12T\n" +
	"\n" +
	"extra_tags\x18\r \x03(\v25.zc8_telemetry_proto_v1.DecodedPayload.ExtraTagsEntryR\textraTags\x12;\n" +
	"\x06fields\x18\x0e \x03(\v2#.zc8_telemetry_proto_v1.SensorFieldR\x06fields\x12\x1d\n" +
	"\n" +
	"service_id\x18\x0f \x01(\x03R\tserviceId\x1a<\n" +
	"\x0eExtraTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x05\n" +
	"\fServiceEvent\x12G\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2(.zc8_telemetry_proto_v1.ServiceEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12!\n" +
	"\fservice_type\x18\x03 \x01(\tR\vserviceType\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\x03R\x05orgId\x12\x17\n" +
	"\ateam_id\x18\x05 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x06 \x01(\tR\bteamName\x12;\n" +
	"\vreported_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x12!\n" +
	"\fis_connected\x18\b \x01(\bR\visConnected\x12\x1d\n" +
	"\n" +
	"is_running\x18\t \x01(\bR\tisRunning\x12#\n" +
	"\rmessage_count\x18\n" +
	" \x01(\x03R\fmessageCount\x12\x1f\n" +
	"\verror_count\x18\v \x01(\x03R\n" +
	"errorCount\x12B\n" +
	"\x0flast_message_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12\x16\n" +
	"\x06broker\x18\r \x01(\tR\x06broker\x12\x16\n" +
	"\x06topics\x18\x0e \x03(\tR\x06topics\x12\x1d\n" +
	"\n" +
	"device_key\x18\x0f \x01(\x04R\tdeviceKey\x12!\n" +
	"\fsource_topic\x18\x10 \x01(\tR\vsourceTopic\x12'\n" +
	"\x0fpayload_preview\x18\x11 \x01(\fR\x0epayloadPreview\x12!\n" +
	"\fpayload_size\x18\x12 \x01(\x05R\vpayloadSize\x12'\n" +
	"\x0frecords_written\x18\x13 \x01(\x05R\x0erecordsWritten\x12\x16\n" +
	"\x06target\x18\x14 \x01(\tR\x06target\"\xc3\t\n" +
	"\x0fCommandEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"device_key\x18\x03 \x01(\x04R\tdeviceKey\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\tR\x06devEui\x12!\n" +
	"\fcommand_type\x18\x05 \x01(\tR\vcommandType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12%\n" +
	"\x0etransport_type\x18\a \x01(\tR\rtransportType\x12*\n" +
	"\x11lns_provider_code\x18\b \x01(\tR\x0flnsProviderCode\x12%\n" +
	"\x0eformatter_code\x18\t \x01(\tR\rformatterCode\x12\x1b\n" +
	"\tmqtt_host\x18\n" +
	" \x01(\tR\bmqttHost\x12\x1b\n" +
	"\tmqtt_port\x18\v \x01(\x05R\bmqttPort\x12#\n" +
	"\rmqtt_username\x18\f \x01(\tR\fmqttUsername\x12#\n" +
	"\rmqtt_password\x18\r \x01(\tR\fmqttPassword\x12\x19\n" +
	"\bmqtt_qos\x18\x0e \x01(\x05R\amqttQos\x12 \n" +
	"\fmqtt_use_tls\x18\x0f \x01(\bR\n" +
	"mqttUseTls\x12\"\n" +
	"\rhttp_base_url\x18\x10 \x01(\tR\vhttpBaseUrl\x12\x1f\n" +
	"\vhttp_method\x18\x11 \x01(\tR\n" +
	"httpMethod\x12$\n" +
	"\x0ehttp_auth_type\x18\x12 \x01(\tR\fhttpAuthType\x122\n" +
	"\x15http_auth_credentials\x18\x13 \x01(\tR\x13httpAuthCredentials\x12(\n" +
	"\x10http_timeout_sec\x18\x14 \x01(\x05R\x0ehttpTimeoutSec\x12*\n" +
	"\x11http_content_type\x18\x15 \x01(\tR\x0fhttpContentType\x12\x1b\n" +
	"\tgrpc_host\x18\x16 \x01(\tR\bgrpcHost\x12\x1b\n" +
	"\tgrpc_port\x18\x17 \x01(\x05R\bgrpcPort\x12*\n" +
	"\x11grpc_service_name\x18\x18 \x01(\tR\x0fgrpcServiceName\x12'\n" +
	"\x0forganization_id\x18\x19 \x01(\x03R\x0eorganizationId\x12\x17\n" +
	"\ateam_id\x18\x1a \x01(\x03R\x06teamId\x12*\n" +
	"\x11device_model_code\x18\x1b \x01(\tR\x0fdeviceModelCode\x12\x1f\n" +
	"\vvendor_code\x18\x1c \x01(\tR\n" +
	"vendorCode\x12'\n" +
	"\x0fdevice_metadata\x18\x1d \x01(\fR\x0edeviceMetadata\x129\n" +
	"\n" +
	"created_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\fmax_attempts\x18  \x01(\x05R\vmaxAttempts\x12\x18\n" +
	"\aattempt\x18! \x01(\x05R\aattempt\"\xbd\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12C\n" +
	"\x0facknowledged_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eacknowledgedAt\"\x97\x01\n" +
	"\tIngestAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\vingest_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestTime\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"Z\n" +
	"\x12IngestBatchRequest\x12D\n" +
	"\tenvelopes\x18\x01 \x03(\v2&.zc8_telemetry_proto_v1.IngestEnvelopeR\tenvelopes\"\x7f\n" +
	"\x0eIngestBatchAck\x125\n" +
	"\x04acks\x18\x01 \x03(\v2!.zc8_telemetry_proto_v1.IngestAckR\x04acks\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x05R\brejected*i\n" +
	"\fIngestSource\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSOURCE_MQTT\x10\x01\x12\x0f\n" +
	"\vSOURCE_GRPC\x10\x02\x12\x0f\n" +
	"\vSOURCE_HTTP\x10\x03\x12\x0e\n" +
	"\n" +
	"SOURCE_CLI\x10\x04*L\n" +
	"\vPayloadType\x12\x17\n" +
	"\x13PAYLOAD_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPAYLOAD_RAW\x10\x01\x12\x13\n" +
	"\x0fPAYLOAD_DECODED\x10\x02*R\n" +
	"\tValueType\x12\x15\n" +
	"\x11VALUE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vVALUE_FLOAT\x10\x01\x12\r\n" +
	"\tVALUE_INT\x10\x02\x12\x0e\n" +
	"\n" +
	"VALUE_BOOL\x10\x03*{\n" +
	"\x10ServiceEventType\x12\x19\n" +
	"\x15SVC_EVENT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSVC_HEARTBEAT\x10\x01\x12\x11\n" +
	"\rSVC_TOMBSTONE\x10\x02\x12\x12\n" +
	"\x0eSVC_RAW_INGEST\x10\x03\x12\x12\n" +
	"\x0eSVC_OUTPUT_ACK\x10\x042\xb4\x02\n" +
	"\x16TelemetryIngestService\x12X\n" +
	"\vIngestUnary\x12&.zc8_telemetry_proto_v1.IngestEnvelope\x1a!.zc8_telemetry_proto_v1.IngestAck\x12]\n" +
	"\fIngestStream\x12&.zc8_telemetry_proto_v1.IngestEnvelope\x1a!.zc8_telemetry_proto_v1.IngestAck(\x010\x01\x12a\n" +
	"\vIngestBatch\x12*.zc8_telemetry_proto_v1.IngestBatchRequest\x1a&.zc8_telemetry_proto_v1.IngestBatchAck2\xce\x01\n" +
	"\x0eCommandService\x12Z\n" +
	"\vSendCommand\x12'.zc8_telemetry_proto_v1.CommandEnvelope\x1a\".zc8_telemetry_proto_v1.CommandAck\x12`\n" +
	"\rCommandStream\x12'.zc8_telemetry_proto_v1.CommandEnvelope\x1a\".zc8_telemetry_proto_v1.CommandAck(\x010\x01B<Z:github.com/rogeriocassares/zc8/packages/proto/telemetry/v1b\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ingest_proto_goTypes = []any{
	(IngestSource)(0),             // 0: zc8_telemetry_proto_v1.IngestSource
	(PayloadType)(0),              // 1: zc8_telemetry_proto_v1.PayloadType
	(ValueType)(0),                // 2: zc8_telemetry_proto_v1.ValueType
	(ServiceEventType)(0),         // 3: zc8_telemetry_proto_v1.ServiceEventType
	(*DeviceTags)(nil),            // 4: zc8_telemetry_proto_v1.DeviceTags
	(*SensorCalibration)(nil),     // 5: zc8_telemetry_proto_v1.SensorCalibration
	(*DeviceContext)(nil),         // 6: zc8_telemetry_proto_v1.DeviceContext
	(*IngestEnvelope)(nil),        // 7: zc8_telemetry_proto_v1.IngestEnvelope
	(*RawPayload)(nil),            // 8: zc8_telemetry_proto_v1.RawPayload
	(*SensorField)(nil),           // 9: zc8_telemetry_proto_v1.SensorField
	(*DecodedPayload)(nil),        // 10: zc8_telemetry_proto_v1.DecodedPayload
	(*ServiceEvent)(nil),          // 11: zc8_telemetry_proto_v1.ServiceEvent
	(*CommandEnvelope)(nil),       // 12: zc8_telemetry_proto_v1.CommandEnvelope
	(*CommandAck)(nil),            // 13: zc8_telemetry_proto_v1.CommandAck
	(*IngestAck)(nil),             // 14: zc8_telemetry_proto_v1.IngestAck
	(*IngestBatchRequest)(nil),    // 15: zc8_telemetry_proto_v1.IngestBatchRequest
	(*IngestBatchAck)(nil),        // 16: zc8_telemetry_proto_v1.IngestBatchAck
	nil,                           // 17: zc8_telemetry_proto_v1.DeviceTags.ExtraEntry
	nil,                           // 18: zc8_telemetry_proto_v1.DecodedPayload.ExtraTagsEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_ingest_proto_depIdxs = []int32{
	17, // 0: zc8_telemetry_proto_v1.DeviceTags.extra:type_name -> zc8_telemetry_proto_v1.DeviceTags.ExtraEntry
	4,  // 1: zc8_telemetry_proto_v1.DeviceContext.tags:type_name -> zc8_telemetry_proto_v1.DeviceTags
	5,  // 2: zc8_telemetry_proto_v1.DeviceContext.calibrations:type_name -> zc8_telemetry_proto_v1.SensorCalibration
	19, // 3: zc8_telemetry_proto_v1.IngestEnvelope.ts:type_name -> google.protobuf.Timestamp
	19, // 4: zc8_telemetry_proto_v1.IngestEnvelope.ingest_ts:type_name -> google.protobuf.Timestamp
	0,  // 5: zc8_telemetry_proto_v1.IngestEnvelope.source:type_name -> zc8_telemetry_proto_v1.IngestSource
	1,  // 6: zc8_telemetry_proto_v1.IngestEnvelope.type:type_name -> zc8_telemetry_proto_v1.PayloadType
	6,  // 7: zc8_telemetry_proto_v1.IngestEnvelope.context:type_name -> zc8_telemetry_proto_v1.DeviceContext
	8,  // 8: zc8_telemetry_proto_v1.IngestEnvelope.raw:type_name -> zc8_telemetry_proto_v1.RawPayload
	10, // 9: zc8_telemetry_proto_v1.IngestEnvelope.decoded:type_name -> zc8_telemetry_proto_v1.DecodedPayload
	2,  // 10: zc8_telemetry_proto_v1.SensorField.value_type:type_name -> zc8_telemetry_proto_v1.ValueType
	18, // 11: zc8_telemetry_proto_v1.DecodedPayload.extra_tags:type_name -> zc8_telemetry_proto_v1.DecodedPayload.ExtraTagsEntry
	9,  // 12: zc8_telemetry_proto_v1.DecodedPayload.fields:type_name -> zc8_telemetry_proto_v1.SensorField
	3,  // 13: zc8_telemetry_proto_v1.ServiceEvent.event_type:type_name -> zc8_telemetry_proto_v1.ServiceEventType
	19, // 14: zc8_telemetry_proto_v1.ServiceEvent.reported_at:type_name -> google.protobuf.Timestamp
	19, // 15: zc8_telemetry_proto_v1.ServiceEvent.last_message_at:type_name -> google.protobuf.Timestamp
	19, // 16: zc8_telemetry_proto_v1.CommandEnvelope.created_at:type_name -> google.protobuf.Timestamp
	19, // 17: zc8_telemetry_proto_v1.CommandEnvelope.expires_at:type_name -> google.protobuf.Timestamp
	19, // 18: zc8_telemetry_proto_v1.CommandAck.acknowledged_at:type_name -> google.protobuf.Timestamp
	19, // 19: zc8_telemetry_proto_v1.IngestAck.ingest_time:type_name -> google.protobuf.Timestamp
	7,  // 20: zc8_telemetry_proto_v1.IngestBatchRequest.envelopes:type_name -> zc8_telemetry_proto_v1.IngestEnvelope
	14, // 21: zc8_telemetry_proto_v1.IngestBatchAck.acks:type_name -> zc8_telemetry_proto_v1.IngestAck
	7,  // 22: zc8_telemetry_proto_v1.TelemetryIngestService.IngestUnary:input_type -> zc8_telemetry_proto_v1.IngestEnvelope
	7,  // 23: zc8_telemetry_proto_v1.TelemetryIngestService.IngestStream:input_type -> zc8_telemetry_proto_v1.IngestEnvelope
	15, // 24: zc8_telemetry_proto_v1.TelemetryIngestService.IngestBatch:input_type -> zc8_telemetry_proto_v1.IngestBatchRequest
	12, // 25: zc8_telemetry_proto_v1.CommandService.SendCommand:input_type -> zc8_telemetry_proto_v1.CommandEnvelope
	12, // 26: zc8_telemetry_proto_v1.CommandService.CommandStream:input_type -> zc8_telemetry_proto_v1.CommandEnvelope
	14, // 27: zc8_telemetry_proto_v1.TelemetryIngestService.IngestUnary:output_type -> zc8_telemetry_proto_v1.IngestAck
	14, // 28: zc8_telemetry_proto_v1.TelemetryIngestService.IngestStream:output_type -> zc8_telemetry_proto_v1.IngestAck
	16, // 29: zc8_telemetry_proto_v1.TelemetryIngestService.IngestBatch:output_type -> zc8_telemetry_proto_v1.IngestBatchAck
	13, // 30: zc8_telemetry_proto_v1.CommandService.SendCommand:output_type -> zc8_telemetry_proto_v1.CommandAck
	13, // 31: zc8_telemetry_proto_v1.CommandService.CommandStream:output_type -> zc8_telemetry_proto_v1.CommandAck
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	file_ingest_proto_msgTypes[3].OneofWrappers = []any{
		(*IngestEnvelope_Raw)(nil),
		(*IngestEnvelope_Decoded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		EnumInfos:         file_ingest_proto_enumTypes,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
