/**
 * Advanced Device Creation Form
 *
 * Features:
 * - Auto-generates device_id (UUIDv7) and device_key
 * - Device type selection (LoRaWAN, MQTT, etc.)
 * - Conditional UI for LoRaWAN (show LNS adapter & deveUI)
 * - Vendor and model dropdowns (vendor-dependent)
 * - Organization and team selection (team depends on org)
 * - Device tags input
 * - Read-only auto-generated fields
 * - Full form validation with error messages
 */

"use client";

import { type ChangeEvent, type FormEvent, useEffect, useState } from "react";

interface DeviceType {
  id: number;
  name: string;
  description?: string;
}

interface Vendor {
  id: number;
  name: string;
  description?: string;
}

interface Organization {
  id: number;
  name: string;
  description?: string;
}

interface Team {
  id: number;
  name: string;
  description?: string;
}

interface LNSAdapter {
  id: number;
  name: string;
}

interface FormData {
  device_type_id: number;
  vendor_id: number | null;
  model: string;
  organization_id: number | null;
  team_id: number | null;
  deveui: string;
  tags: string[];
  lns_adapter_id: number | null;
}

interface AutoGeneratedFields {
  device_id: string;
  device_key: string;
}

export function DeviceCreationForm() {
  // Form State
  const [formData, setFormData] = useState<FormData>({
    device_type_id: 1001, // Default: LoRaWAN
    vendor_id: null,
    model: "",
    organization_id: null,
    team_id: null,
    deveui: "",
    tags: [],
    lns_adapter_id: 1001, // Default: ChirpStack
  });

  const [autoFields, setAutoFields] = useState<AutoGeneratedFields>({
    device_id: "",
    device_key: "",
  });

  // Dropdown Data
  const [deviceTypes, setDeviceTypes] = useState<DeviceType[]>([]);
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [models, setModels] = useState<string[]>([]);
  const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [teams, setTeams] = useState<Team[]>([]);
  const [lnsAdapters, setLnsAdapters] = useState<LNSAdapter[]>([]);

  // UI State
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [tagInput, setTagInput] = useState("");

  // Generate UUIDv7 and compute device_key
  useEffect(() => {
    const generateUUID = (): string => {
      const timestamp = Date.now();
      const randomParams = crypto.getRandomValues(new Uint8Array(8));

      // Basic UUIDv7 format
      const time_hi = (timestamp >> 32) & 0xffffffff;
      const time_mid = (timestamp >> 16) & 0xffff;
      const time_low = (timestamp & 0xffff) | 0x7000; // Version 7

      const node = Array.from(randomParams)
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");

      return `${time_hi.toString(16).padStart(8, "0")}-${time_mid.toString(16).padStart(4, "0")}-${time_low.toString(16).padStart(4, "0")}-${node.slice(0, 4)}-${node.slice(4)}`;
    };

    const computeDeviceKey = (uuid: string): string => {
      // Parse UUIDv7 to DeviceKey (lower 64 bits)
      if (uuid.length !== 36) return "0";

      let result = 0n;

      const fromHex = (c: string): number => {
        const code = c.charCodeAt(0);
        if (code >= 48 && code <= 57) return code - 48; // '0'-'9'
        if (code >= 97 && code <= 102) return code - 97 + 10; // 'a'-'f'
        if (code >= 65 && code <= 70) return code - 65 + 10; // 'A'-'F'
        return -1;
      };

      // Lower 64 bits: indices 19-22 (4 chars) + 24-35 (12 chars)
      for (let i = 19; i < 23; i++) {
        result = (result << 4n) | BigInt(fromHex(uuid[i]));
      }
      for (let i = 24; i < 36; i++) {
        result = (result << 4n) | BigInt(fromHex(uuid[i]));
      }

      return result.toString();
    };

    const deviceId = generateUUID();
    const deviceKey = computeDeviceKey(deviceId);

    setAutoFields({
      device_id: deviceId,
      device_key: deviceKey,
    });
  }, []);

  // Load initial dropdown data
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        const [vendorsRes, orgsRes] = await Promise.all([
          fetch("/api/vendors"),
          fetch("/api/organizations"),
        ]);

        if (!vendorsRes.ok || !orgsRes.ok) {
          throw new Error("Failed to load dropdown data");
        }

        const vendors = await vendorsRes.json();
        const orgs = await orgsRes.json();

        setVendors(vendors.vendors || []);
        setOrganizations(orgs.organizations || []);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to load form data",
        );
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Load models when vendor changes
  useEffect(() => {
    if (!formData.vendor_id) {
      setModels([]);
      return;
    }

    const loadModels = async () => {
      try {
        const res = await fetch(`/api/vendors/${formData.vendor_id}/models`);
        if (!res.ok) throw new Error("Failed to load models");
        const data = await res.json();
        setModels(data.models || []);
        if (data.models && data.models.length > 0) {
          setFormData((prev) => ({ ...prev, model: data.models[0] }));
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load models");
      }
    };

    loadModels();
  }, [formData.vendor_id]);

  // Load teams when organization changes
  useEffect(() => {
    if (!formData.organization_id) {
      setTeams([]);
      return;
    }

    const loadTeams = async () => {
      try {
        const res = await fetch(
          `/api/organizations/${formData.organization_id}/teams`,
        );
        if (!res.ok) throw new Error("Failed to load teams");
        const data = await res.json();
        setTeams(data.teams || []);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load teams");
      }
    };

    loadTeams();
  }, [formData.organization_id]);

  // Validate DevEUI: must be 16 hex characters (8 bytes)
  const validateDevEUI = (deveui: string): boolean => {
    const hexRegex = /^[0-9A-Fa-f]{16}$/;
    return hexRegex.test(deveui);
  };

  // Handle device type change
  const handleDeviceTypeChange = (e: ChangeEvent<HTMLSelectElement>) => {
    const typeId = parseInt(e.target.value);
    setFormData((prev) => ({
      ...prev,
      device_type_id: typeId,
      // Reset LNS adapter if not LoRaWAN
      lns_adapter_id: typeId === 1001 ? prev.lns_adapter_id : null,
      deveui: typeId === 1001 ? prev.deveui : "",
    }));
  };

  // Handle form field changes
  const handleInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]:
        name === "vendor_id" || name === "organization_id"
          ? value
            ? parseInt(value)
            : null
          : name === "team_id"
            ? value
              ? parseInt(value)
              : null
            : name === "lns_adapter_id"
              ? value
                ? parseInt(value)
                : null
              : value,
    }));
  };

  // Handle tag input
  const handleAddTag = () => {
    if (tagInput.trim()) {
      setFormData((prev) => ({
        ...prev,
        tags: [...prev.tags, tagInput.trim()],
      }));
      setTagInput("");
    }
  };

  const handleRemoveTag = (index: number) => {
    setFormData((prev) => ({
      ...prev,
      tags: prev.tags.filter((_, i) => i !== index),
    }));
  };

  // Form submission
  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);

    try {
      setIsSubmitting(true);

      // Validation
      if (!formData.organization_id) {
        throw new Error("Organization is required");
      }
      if (formData.device_type_id === 1001) {
        if (!formData.deveui) {
          throw new Error(
            "Device EUI (DevEUI) is required for LoRaWAN devices",
          );
        }
        if (!validateDevEUI(formData.deveui)) {
          throw new Error(
            "Invalid Device EUI: must be exactly 16 hexadecimal characters (8 bytes)",
          );
        }
      }

      // Get tenant ID from organization
      const tenantId = formData.organization_id;

      const payload = {
        device_type_id: formData.device_type_id,
        deveui: formData.deveui || null,
        vendor_id: formData.vendor_id,
        model: formData.model,
        organization_id: tenantId,
        team_id: formData.team_id,
        tags: formData.tags,
        lns_adapter_id: formData.lns_adapter_id,
      };

      const res = await fetch(`/api/tenants/${tenantId}/devices`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to create device");
      }

      setSuccess(
        `Device created successfully! ID: ${data.device.id}, Key: ${data.device.device_key}`,
      );

      // Reset form
      setFormData({
        device_type_id: 1001,
        vendor_id: null,
        model: "",
        organization_id: null,
        team_id: null,
        deveui: "",
        tags: [],
        lns_adapter_id: 1001,
      });

      // Generate new device_id and device_key
      const timestamp = Date.now();
      const randomParams = crypto.getRandomValues(new Uint8Array(8));
      const time_hi = (timestamp >> 32) & 0xffffffff;
      const time_mid = (timestamp >> 16) & 0xffff;
      const time_low = (timestamp & 0xffff) | 0x7000;
      const node = Array.from(randomParams)
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
      const newId = `${time_hi.toString(16).padStart(8, "0")}-${time_mid.toString(16).padStart(4, "0")}-${time_low.toString(16).padStart(4, "0")}-${node.slice(0, 4)}-${node.slice(4)}`;
      setAutoFields({ device_id: newId, device_key: "0" }); // Simplified for demo
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error creating device");
    } finally {
      setIsSubmitting(false);
    }
  };

  const isLoRaWAN = formData.device_type_id === 1001;

  if (loading) {
    return <div className="p-4">Loading form data...</div>;
  }

  return (
    <div className="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow">
      <h1 className="text-2xl font-bold mb-2">Create New Device</h1>
      <p className="text-gray-600 mb-6 text-sm">
        Add a new device to your organization. For LoRaWAN devices, enter a
        valid 8-byte DevEUI. All fields with * are required. Devices are always
        active when created.
      </p>

      {error && (
        <div className="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded">
          {error}
        </div>
      )}

      {success && (
        <div className="mb-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded">
          {success}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Auto-Generated Fields (Read-Only) */}
        <div className="grid grid-cols-2 gap-4 p-4 bg-gray-50 rounded">
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Device ID (Auto-Generated)
            </label>
            <input
              type="text"
              value={autoFields.device_id}
              readOnly
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded bg-gray-100 text-gray-600 text-xs"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Device Key (Auto-Computed)
            </label>
            <input
              type="text"
              value={autoFields.device_key}
              readOnly
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded bg-gray-100 text-gray-600 text-xs"
            />
          </div>
        </div>

        {/* Organization Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Organization *
          </label>
          <select
            name="organization_id"
            value={formData.organization_id || ""}
            onChange={handleInputChange}
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            required
          >
            <option value="">Select an organization</option>
            {organizations.map((org) => (
              <option key={org.id} value={org.id}>
                {org.name}
              </option>
            ))}
          </select>
        </div>

        {/* Team Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Team (Optional)
          </label>
          <select
            name="team_id"
            value={formData.team_id || ""}
            onChange={handleInputChange}
            disabled={!formData.organization_id}
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 disabled:bg-gray-100"
          >
            <option value="">Select a team</option>
            {teams.map((team) => (
              <option key={team.id} value={team.id}>
                {team.name}
              </option>
            ))}
          </select>
        </div>

        {/* Device Type Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Device Type *
          </label>
          <div className="mt-2 space-y-2">
            <label className="flex items-center">
              <input
                type="radio"
                name="device_type"
                value="1001"
                checked={formData.device_type_id === 1001}
                onChange={() =>
                  setFormData((prev) => ({
                    ...prev,
                    device_type_id: 1001,
                    lns_adapter_id: 1001,
                  }))
                }
                className="mr-2"
              />
              <span>LoRaWAN</span>
            </label>
            <label className="flex items-center">
              <input
                type="radio"
                name="device_type"
                value="3001"
                checked={formData.device_type_id === 3001}
                onChange={() =>
                  setFormData((prev) => ({
                    ...prev,
                    device_type_id: 3001,
                    deveui: "",
                    lns_adapter_id: null,
                  }))
                }
                className="mr-2"
              />
              <span>MQTT</span>
            </label>
          </div>
        </div>

        {/* LoRaWAN Specific Fields */}
        {isLoRaWAN && (
          <>
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Device EUI (DevEUI) *
              </label>
              <input
                type="text"
                name="deveui"
                value={formData.deveui}
                onChange={handleInputChange}
                placeholder="Enter 8 bytes (16 hex chars), e.g., 70B3D57ED006A1B0"
                className={`mt-1 w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 font-mono uppercase ${
                  formData.deveui && !validateDevEUI(formData.deveui)
                    ? "border-red-500 bg-red-50"
                    : "border-gray-300"
                }`}
                required
                maxLength={16}
              />
              <p className="mt-1 text-xs text-gray-500">
                8 bytes = 16 hexadecimal characters (0-9, A-F)
              </p>
              {formData.deveui && !validateDevEUI(formData.deveui) && (
                <p className="mt-1 text-xs text-red-600">
                  Invalid: Must be exactly 16 hexadecimal characters
                </p>
              )}
              {formData.deveui && validateDevEUI(formData.deveui) && (
                <p className="mt-1 text-xs text-green-600">✓ Valid DevEUI</p>
              )}
            </div>
          </>
        )}

        {/* Vendor Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Vendor (Optional)
          </label>
          <select
            name="vendor_id"
            value={formData.vendor_id || ""}
            onChange={handleInputChange}
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
          >
            <option value="">Select a vendor</option>
            {vendors.map((vendor) => (
              <option key={vendor.id} value={vendor.id}>
                {vendor.name}
              </option>
            ))}
          </select>
        </div>

        {/* Model Selection (depends on vendor) */}
        {formData.vendor_id && (
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Model
            </label>
            <select
              name="model"
              value={formData.model}
              onChange={handleInputChange}
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">Select a model</option>
              {models.map((model) => (
                <option key={model} value={model}>
                  {model}
                </option>
              ))}
            </select>
          </div>
        )}

        {/* Tags Input */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            Tags
          </label>
          <div className="flex gap-2 mt-1">
            <input
              type="text"
              value={tagInput}
              onChange={(e) => setTagInput(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && handleAddTag()}
              placeholder="Add a tag..."
              className="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            />
            <button
              type="button"
              onClick={handleAddTag}
              className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600"
            >
              Add
            </button>
          </div>
          {formData.tags.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-2">
              {formData.tags.map((tag, index) => (
                <span
                  key={index}
                  className="inline-flex items-center gap-2 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm"
                >
                  {tag}
                  <button
                    type="button"
                    onClick={() => handleRemoveTag(index)}
                    className="text-blue-600 hover:text-blue-800"
                  >
                    ✕
                  </button>
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Submit Button */}
        <button
          type="submit"
          disabled={isSubmitting}
          className="w-full px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:bg-gray-400 font-medium"
        >
          {isSubmitting ? "Creating Device..." : "Create Device"}
        </button>
      </form>
    </div>
  );
}
